### ISSUE TITLE
Word loses track of document on focus loss (and doesn't regain it)

### ISSUE THREAD

**Issue by MiniDigger** [Terminal/DiscordForOffice#3]
Running office 365 business 1810 (11001.20108 Click-and-go) on windows 10 pro 17134.

When I start word and open a document, it shows up in discord just fine, but whenever I switch to another window, it shows up as no file open.

Not sure if there is a way to grab logs that would help identifying the issue, let me know if such a log exist.

**Comment by lepon01** [comment]
No logs exist, but you can help if you sent a video showing the issue in motion

**Comment by MiniDigger** [comment]
there you go https://cdn-b-east.streamable.com/video/mp4/wv1b6.mp4?token=72WizO-dmmmozpp7tukBbg&expires=1543502757

**Comment by clu7ch3r** [comment]
Having the same issue here

**Comment by lepon01** [comment]
I believe this is an issue that affects Office 2016. Am installing it now...

**Comment by lepon01** [comment]
![image](https://user-images.githubusercontent.com/13886925/49624310-d4935180-f9c8-11e8-8cd3-1fd8aa8542cc.png)
Please check you have the latest version `1.0.2.5` which I just deployed instead of `1.0.2.3`

If it's not installed, try opening Word and closing it, before checking again.
If it hasn't updated, uninstall and download again.

If it still doesn't work, please reply

**Comment by lepon01** [comment]
Have a video with me trying to reproduce with the latest version.
I am therefore deeming that it is no longer an issue.

If it is an issue, please scream and shout on the same repo.

https://its-not-advertising-if-the-website-doesnt-exist-anymore.moustacheminer.com/2018-12-07_02-39-05.mp4
